### ISSUE TITLE
Sometimes linebreaks are handled incorrectly

### ISSUE THREAD

**Issue by g3335491** [nodegin/lihkg-web#28]
Sometimes linebreaks (`<br />`) immediately after links and/or images get removed incorrectly.

Also, when quoting certain messages, linebreaks (`"\n"`) after  links and/or images may be doubled sometimes.

Example: \#266 on https://lihkg.na.cx/thread/1465/page/11

**Comment by nodegin** [comment]
Fixed, closing this

**Comment by g3335491** [comment]
Is this really fixed?

**Comment by nodegin** [comment]
@g3335491 I believe so

**Comment by g3335491** [comment]
It seems to me that quoting still adds tons of linebreaks to the quoted message., even when there are no links or images... but perhaps it is a separated issue?

**Comment by nodegin** [comment]
@g3335491 Can you give me the link to the thread?

**Comment by g3335491** [comment]
Really just quoting any replies that contains linebreaks...
