### ISSUE TITLE
[Request] Image gallery

### ISSUE THREAD

**Issue by tsangwailam** [nodegin/lihkg-web#41]
Show all images in post with gallery. Like the one in official apps.

**Comment by chewong** [comment]
I can try to do this

**Comment by chewong** [comment]
I currently have a working version of gallery mode (still a little modification before creating a PR) Check it out if u want! https://github.com/chewong/lihkg-web/tree/gallery_mode

**Comment by nodegin** [comment]
@chewong will check it out tonight!

**Comment by chewong** [comment]
test: https://6270b7fe.ngrok.io/

**Comment by tsangwailam** [comment]
May be better to have a photo grid? The UX is not good in mobile now.

**Comment by chewong** [comment]
Fixed: 
![image](https://cloud.githubusercontent.com/assets/10557231/21081868/bd81305a-bf9d-11e6-8299-98795b94ec81.png)
![image](https://cloud.githubusercontent.com/assets/10557231/21081870/c06826d4-bf9d-11e6-9505-ec99b529468a.png)
can try it here: https://2a56f7a7.ngrok.io/thread/31034/page/40

**Comment by tsangwailam** [comment]
Is it possible to implements the goto photo position feature?
