### ISSUE TITLE
[Comment] About double click menu

### ISSUE THREAD

**Issue by mickmak-busicat** [nodegin/lihkg-web#42]
There maybe somebody is trying to improve the menu. lol I just got some opinion about it after use. I hope some would be able to help to make it better.

I think the menu should be assistance of main features instead of replacing them. For example, the floating buttons is easy to use to reply/open a topic. It is better to remain in the layout and the menu is another optional way to trigger these features whenever users want it.

Double click + hold + drag to trigger a function is quite a tired control. I think it can be more simple like just double click + hold and the menu remains until next action or implement single right click etc.

It is just my personal opinion. But I know the menu will be a good function when we can figure out a good UX for it. Let's try it out together 👍

**Comment by nodegin** [comment]
Hi, I have added the reply button back in latest commit.

Double click + hold + drag mechanism is mainly designed for touch-enabled devices to allow moving the finger onto the selection target, and it working the same way in mouse-based environment.

**Comment by mickmak-busicat** [comment]
Yeah touch is working well. I think it is better to focus more on desktop version as most of the users should be using desktop lol

**Comment by nodegin** [comment]
Now bringing this feature as an accessibility in addition to normal UI elements (buttons, links)
