### ISSUE TITLE
Cannot use double-click and drag to highlight text

### ISSUE THREAD

**Issue by g3335491** [nodegin/lihkg-web#44]
In most desktop browsers, double-click and drag is a built-in function to highlight text which automatically snap the selection to word boundaries. This is also present in most text editing software.

With the addition of the double-click and hold menu, the said function (on at least Chrome and Firefox) is broken.

**Comment by nodegin** [comment]
The workaround should be double-click then holding Shift key and drag the cursor.

**Comment by g3335491** [comment]
It doesn't work at all.

**Comment by g3335491** [comment]
Also, having to hold Shift is not intuitive at all. Please fix this properly.
