### ISSUE TITLE
[Request] Add Lomoji in new/reply message

### ISSUE THREAD

**Issue by tsangwailam** [nodegin/lihkg-web#46]
Add Lomoji in emotions.js
https://lihkg.na.cx/thread/35279/page/15

**Comment by soumasandesu** [comment]
I think in long term, those emotions (traditional 'icons' and Lomojis should be categorised and separated as tabs for convenience to users. 
You know, scrolling pages just to find an 'icon' is frustrating to everyone.

**Comment by tsangwailam** [comment]
Don't know if lihkg can have api to query the lomoji set. It much better to have the same set of emoji and allow auto update if more emoji added.

**Comment by soumasandesu** [comment]
@tsangwailam perhaps just an email to request

**Comment by nodegin** [comment]
Added lomoji icon set. For API need to reach LIHKG admin.
